[package]
name = "AdventOfCode25"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
anyhow = "1.0.100"
itertools = "0.14.0"
